### ISSUE TITLE
Support for forums without email verification

### ISSUE THREAD

**Issue by JustAGuy7** [marttiphpbb/phpbb-ext-pruneinactiveusers#1]
Hi,

Would it be possible to use this extention on a forum without email verification. If I read it right the extention only works when email activation is used on the forum. Would it be possible to have this extention work with users with 0 posts after a certain amount of days or something smimular.

John

**Comment by marttiphpbb** [comment]
That's correct. This extension is for forums with email verification. Users with zero posts is another use case and it would be better to have a separate extension for that.
